FROM node:alpine
MAINTAINER Farhan Sajid <farhansajid7861@gmail.com>

WORKDIR /app
# Copying and installing the dependencies
COPY package.json .
RUN npm install

# Copy the rest
COPY . .

CMD ["npm", "start"]